[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
